### ISSUE TITLE
$ Character gets escaped twice

### ISSUE THREAD

**Issue by Rigo-m** [danielroe/magic-regexp#109]
### 🐛 The bug

`exactly('$')` gets compiled to `\\$`, it should be just `\$`

### 🛠️ To reproduce

https://stackblitz.com/edit/github-rujd5h?file=package-lock.json,index.mjs

### 🌈 Expected behaviour

`exactly('$')` should compile to `\$`

**Comment by danielroe** [comment]
Ah. The issue here is that `at.lineStart` is a function:

```diff
- const DOLLAR_RE = createRegExp(exactly('$').at.lineStart);
+ const DOLLAR_RE = createRegExp(exactly('$').at.lineStart());
```

**Comment by danielroe** [comment]
You should get a type error something like:

```
