### ISSUE TITLE
`createRegExp` not sanitising strings (in type)

### ISSUE THREAD

**Issue by danielroe** [danielroe/magic-regexp#160]
`createRegExp('.com')` should return the same type as `createRegExp(exactly('.com'))`

**Comment by TheTrio** [comment]
Hi. 

If I understand the problem correctly, I assume I'll have to make a new type similar to `Join` in `src/core/types/join.ts`? I imagine that being quite complicated though, so is there a better/easier way here?

**Comment by TheTrio** [comment]
Hi.

If I understand this problem correctly, the way to solve it would be to create a new sanitizing type similar to the `Join` type in `src/core/types/join.ts`

However, I imagine that that would be complicated to implement, so is there a better/more straightforward way here?
