### ISSUE TITLE
Library blocks Typescript compilation 

### ISSUE THREAD

**Issue by akowi-sknobloch** [danielroe/magic-regexp#287]
### 🐛 The bug

When Trying to build a Typescript Project using magic-regexp tsc hangs indefinitely.
It just hangs and does nothing.

The Problem occurred in different projects (finding the problem the first time did cost me a good amount of time).

### 🛠️ To reproduce

https://stackblitz.com/edit/github-dmq6xe?file=package.json

### 🌈 Expected behaviour

The build Process should go through or at least throw an error.

### ℹ️ Additional context

When using ts-node to run the Script it works for whatever reason.

I've added a `build` script & a `start:ts-node` script to the example.

**Comment by didavid61202** [comment]
Hi @akowi-sknobloch,

can you try adding `"skipLibCheck": true` in `tsconfig` and see if this resolve the issue?

thanks

**Comment by akowi-sknobloch** [comment]
Alright seems like `"skipLibCheck": true` does the trick.
Does now compile without any issues.
Thank you!
