### ISSUE TITLE
adblocker stops the homepage

### ISSUE THREAD

**Issue by Geczy** [danielroe/magic-regexp#36]
### 🐛 The bug

500
Failed to fetch dynamically imported module: https://magic-regexp.roe.dev/_nuxt/fluid-d2d9e9d9.mjs

### 🛠️ To reproduce

https://magic-regexp.roe.dev/

### 🌈 Expected behaviour

load the homepage

### ℹ️ Additional context

ublock origin

**Comment by danielroe** [comment]
How strange!
