### ISSUE TITLE
Does the look behind operator work with safari?

### ISSUE THREAD

**Issue by antlionguard** [danielroe/magic-regexp#4]
I saw this example on the documentation.

```ts
import { createRegExp, exactly } from 'magic-regexp'

const regExp = createRegExp(exactly('foo/test.js').after('bar/'))
console.log(regExp)

// /(?<=bar\/)foo\/test\.js/
```

This example can work with safari?

**Comment by antlionguard** [comment]
This was a documentated. My bad.

**Comment by danielroe** [comment]
No, Safari does not yet support lookbehind. Probably would be useful to add to JSDoc so it gets surfaced when in use...
